### ISSUE TITLE
RBF Coarsening: save selected points in pointZone in OpenFOAM for reuse or plotting (when requested?)

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#12]
To see which points are selected for RBF motion a pointZone would be ideal, since a pointZone can be opened by paraview.

**Comment by davidsblom** [comment]
Do you have some hints on how to implement this? Not really familiar with pointZones.

**Comment by thijsgillebaart** [comment]
I never programmed pointZones, only created them from sets using the utility setsToZones. So I would start with looking at that utility. Next week I will check it out myself, but I though lets add it to the issue list :).

**Comment by davidsblom** [comment]
I've made a simple implementation to dump the positions matrix to disk. The exportSelectedPoints option should be set in the dynamicMeshDictFile.
This is an example python script to visualize the points for a 3d test case with matplotlib.

``` python
#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import axes3d

positions = np.loadtxt( "fluid/rbf-coarsening-greedy-selection-0.txt" )

fig = plt.figure()
ax = fig.gca( projection='3d' )
ax.plot( positions[:,0], positions[:,1], positions[:,2], 'o' )

positions = np.loadtxt( "fluid/rbf-coarsening-greedy-selection-1.txt" )

fig = plt.figure()
ax = fig.gca( projection='3d' )
ax.plot( positions[:,0], positions[:,1], positions[:,2], 'o' )

plt.show()
```

**Comment by davidsblom** [comment]
write the data out as a csv file

**Comment by davidsblom** [comment]
```
CSV output is already possible, using something like this:
  IOFormat CSVFmt(FullPrecision, 0, ", ");
// or
  IOFormat CSVFmt(FullPrecision, DontAlignCols, ",\t");
// and then
  std::cout << A.format(CSVFmt);
```
