### ISSUE TITLE
Use $PRECICE_ROOT environment variable

### ISSUE THREAD

**Issue by davidsblom** [davidsblom/FOAM-FSI#149]
Use `$PRECICE_ROOT` if the environment variable is set, otherwise use the local install of precice in `src/thirdParty/precice`

**Comment by dlutyezhang** [comment]
Hi David, 

I have some problem to compile precice. It gives error like this:
--------------------------------------------------------------------------------
ye@thirdParty$./compile_precice
scons: Reading SConscript files ...

Build options ...
(default)  builddir                  = build      Directory holding build files. ( /path/to/builddir )
(modified) build                     = release    Build type, either release or debug (release|debug)
(modified) compiler                  = mpicxx     Compiler to use.
(default)  mpi                       = True       Enables MPI-based communication and running coupling tests. (yes|no)
(default)  sockets                   = True       Enables Socket-based communication. (yes|no)
(default)  boost_inst                = False      Enable if Boost is available compiled and installed. (yes|no)
(default)  spirit2                   = True       Used for parsing VRML file geometries and checkpointing. (yes|no)
(modified) petsc                     = False      Enable use of the Petsc linear algebra library. (yes|no)
(modified) python                    = False      Used for Python scripted solver actions. (yes|no)
(default)  gprof                     = False      Used in detailed performance analysis. (yes|no)
... done

Environment variables used for this build ...
(have to be defined by the user to configure build)
(modified) PRECICE_BOOST_ROOT        = /home/ye/foam/foam-extend-3.2/src/FOAM-FSI/src/thirdParty/boost_1_55_0
(modified) PRECICE_MPI_LIB_PATH      = /home/ye/foam/foam-extend-3.2/ThirdParty/packages/openmpi-1.6.5/platforms/linux64GccDPOpt/lib
(modified) PRECICE_MPI_LIB           = mpi     
(modified) PRECICE_MPI_INC_PATH      = /home/ye/foam/foam-extend-3.2/ThirdParty/packages/openmpi-1.6.5/platforms/linux64GccDPOpt/include
(default)  PRECICE_PTHREAD_LIB_PATH  = /usr/lib
(default)  PRECICE_PTHREAD_LIB       = pthread 
(default)  PRECICE_PTHREAD_INC_PATH  = /usr/include
... done

Configuring build variables ...
Checking whether the C++ compiler worksno
-----------------------------------------------------------------
Do you know how to fixed it? I use Ubuntu 14.04, thanks!

**Comment by thijsgillebaart** [comment]
you have to use the system openmpi to fix it now. (Also for compiling
foam-extend-3.2)

@david: maybe make a issue for this

**Comment by davidsblom** [comment]
hi!

I've updated the readme, but it's not yet in the master branch. you can read it here. 

https://github.com/davidsblom/FOAM-FSI/blob/480ac36495c0c6cfc920f7a2e22cf9feccfab7d4/README.md

as thijs mentioned, you should use the system openmpi in order to be able to use precice.
