### ISSUE TITLE
SDC: use a BDF2 predictor in order to decrease the number of SDC sweeps

### ISSUE THREAD

**Issue by davidsblom** [davidsblom/FOAM-FSI#18]
The predictor of SDC is only used to compute the provisional solution, so the initial solution for every sub step. The standard Euler integrator is used in the correction steps. See papers by Layton and Minion for studies on the used predictor and corrector of varying orders.

**Comment by davidsblom** [comment]
The best approach is to implement the BDF2 predictor for the simple piston. Add a test in the googletest suite which verifies that the number of correction sweeps is decreased when the BDF2 predictor is used.
Thereafter, implement the functionality in the incompressible flow solver.

**Comment by davidsblom** [comment]
http://people.cs.vt.edu/~asandu/Public/For/Michael/Layton_2008_Picard.pdf

**Comment by davidsblom** [comment]
the coefficients for BDF2 can be found here:

http://dc.uwm.edu/cgi/viewcontent.cgi?article=1405&context=etd

**Comment by davidsblom** [comment]
some numerical experiments showed an increase in computational time...

**Comment by thijsgillebaart** [comment]
that’s a shame. Would have been nice….
