### ISSUE TITLE
RBFMeshMotionSolver: add parameter fixedPatches

### ISSUE THREAD

**Issue by davidsblom** [davidsblom/FOAM-FSI#20]
The displacement of the vertices of the staticPatches are manually set to zero. Add a list of fixedPatches for which the displacement is interpolated, i.e. zero displacement on the faces is interpolated to the vertices.

**Comment by davidsblom** [comment]
@thijsgillebaart Can you verify whether the implementation works correctly for the airfoil flap test case?

**Comment by thijsgillebaart** [comment]
@davidsblom Yes it works correctly :+1:

**Comment by davidsblom** [comment]
top!
