### ISSUE TITLE
RBF mesh deformation: all-to-all communication step of boundary points for error calculation results in too large memory usage

### ISSUE THREAD

**Issue by scheufks** [davidsblom/FOAM-FSI#258]
shared_exafsa/3dTube_MESH-L6_1 test case folder.

**Comment by davidsblom** [comment]
when doing weak scalability tests on supermuc, the error calculation step for the selection of points results in a all-to-all communication step of all points on the interface. this most probably results in a memory usage problem.

**Comment by davidsblom** [comment]
the solution would be to compute the errors locally, and communicate the locally selected point to the other cpus. the global selected point is then communicated to the other cpus.

**Comment by davidsblom** [comment]
**Cause of problem:**
With the current implementation of the RBF mesh deformation algorithm, all the boundary points are collected on each processor. This happens in the RBFMeshMotionSolver class during the initialisation step. Hence, the memory usage increases substantially per MPI rank for a weak scaling study.

**Solution:**
Complete rewrite of the RBFMeshMotionSolver, RBFCoarsening and RBFInterpolation class. This is probably not a small task. The meshes need to be distributed over the MPI ranks using trilinos or PETSc.

**Comment by davidsblom** [comment]
My current idea is to use Elemental [http://libelemental.org/](http://libelemental.org/) which implements distributed dense linear algebra algorithms. The API is similar to Eigen.

**Comment by davidsblom** [comment]
I've implemented a new ElRBFMeshMotion solver which uses the elemental library. All data is now distributed just like in PETSc. Hopefully, this case can now also be run on supermuc. Still updating the compilation scripts for supermuc.

**Comment by davidsblom** [comment]
@scheufks can you update the permissions of the files in `/shared_exafsa/3dTube_MESH-L6_1`? I cannot read all files.

**Comment by scheufks** [comment]
does it work now?

**Comment by davidsblom** [comment]
yes. thanks!

**Comment by davidsblom** [comment]
it runs now with the ElRBFMeshMotionSolver
