### ISSUE TITLE
Optimize performance of RBF evaluation

### ISSUE THREAD

**Issue by davidsblom** [davidsblom/FOAM-FSI#30]
@thijsgillebaart

**Comment by davidsblom** [comment]
commit 1e75f56ccebe3759edc73228c381c2b59f275773

**Comment by davidsblom** [comment]
commit 1968bfae395b8312a6eae556d0f82d0d17fbff02

Gebruik de cholesky decomposition tijdens de greedy stappen wanneer een Wendland RBF functie wordt gebruikt.

**Comment by davidsblom** [comment]
small test to evaluate parallel performance:

1 core: timing mesh deformation = 15.0168 s
2 cores: timing mesh deformation = 8.63279 s
4 cores: timing mesh deformation = 7.62925 s

timing LU decomposition =  1.37993 s. not influenced by the number of cores

surprisingly, on 1 core the matrix matrix multiplication is dominant: 5.7s
``` c++
Hhat.noalias() = Phi * Hinverse;
```

evaluation of RBF matrices slowly starts to dominate with an increasing number of cores.

**Comment by davidsblom** [comment]
check SSE optimization compilation flags

@thijsgillebaart 

http://stackoverflow.com/questions/20150257/does-gcc-4-8-1-enable-sse-by-default

**Comment by davidsblom** [comment]
https://software.intel.com/en-us/blogs/2012/09/26/gcc-x86-performance-hints

extra compilation flags:
`-m64 -Ofast -flto -march=native -funroll-loops`

decrease from 5s to 1.99s with a quick test!

**Comment by davidsblom** [comment]
correctie. van 2.05 naar 1.99...

**Comment by thijsgillebaart** [comment]
heb wel beetje zitten kijken, maar nog niet echt kunnen testen. Flag (-march=native) werkt niet op mac. Heb zojuist wel test ding afgemaakt in C++ met eigen zoals ik die in matlab had. Vergelijkbare resultaten, behalve the CPU evaluatie elke tijdstap gaat stukken sneller. Nog steeds factor 10 tot 20 ten opzichte van memory formulatie. En voor mij duurt een Phi*Hinverse van [131841, 257] x [257 x 257] ongeveer 1.7 s

**Comment by davidsblom** [comment]
test met wat meer info:
```

RBF interpolation coarsening: selected 257/8000 points, error = 0.026097, tol = 1e-09
positions = 257 x 3
positionsInterpolation = 137011 x 3
evaluate H = 0.00173 s
evaluate Phi = 1.66274 s
inversion H = 0.005698 s
Phi = 137011 x 261
Hinverse = 261 x 261
compute Hhat = 1.53734 s
timing mesh deformation = 4.61663 s
```

**Comment by thijsgillebaart** [comment]
Ziet er ongeveer het zelfde uit als matlab en mijn test. Heb jij nog
problemen met de uitkomst?

**Comment by davidsblom** [comment]
niet echt. zal nog even een test doen met die extra compilation flags. verwacht niet veel verschil. denk dat de implementatie dan toch wel prima is. de selectie blijft denk ik vrij duur doordat je meerdere keren vrijwel het hele proces doorloopt.

**Comment by davidsblom** [comment]
dezelfde test met extra compilation flags voor performance:

```
RBF interpolation coarsening: selected 257/8000 points, error = 0.026097, tol = 1e-09
positions = 257 x 3
positionsInterpolation = 137011 x 3
1. evaluate H = 0.001801 s
2. evaluate Phi = 1.70288 s
3. inversion H = 0.005781 s
Phi = 137011 x 261
Hinverse = 261 x 261
4. compute Hhat = 1.53726 s
5. interpolation = 0.095218 s
timing mesh deformation = 4.54856 s
```

geen grote verschillen.
