### ISSUE TITLE
Problem compilation FOAM-FSI with Allwmake.firstInstall: unbound variable

### ISSUE THREAD

**Issue by SvensenSeven** [davidsblom/FOAM-FSI#354]
After compilation of foam-extend-3.2 on Ubuntu 14.04 system I've tried to compile FOAM-FSI library. But suddenly I've got an error like this:

++ export WM_THIRD_PARTY_USE_PARAVIEW_431=1
++ WM_THIRD_PARTY_USE_PARAVIEW_431=1
++ '[' POSIX == MSWindows ']'
++ '[' -e /home/sergey/foam-extend/foam-extend-3.2/etc/prefs.sh ']'
++ _foamSource /home/sergey/foam-extend/foam-extend-3.2/etc/prefs.sh
++ '[' 1 -ge 1 ']'
/home/sergey/foam-extend/foam-extend-3.2/src/../etc/bashrc: line 122: PS1: unbound variable

The same problem was with FOAM_USER_SRC variable in the if [ -z ...] statement, but I simply commented these "if" "fi" lines.

However source foam-extend-3.2/etc/bashrc work without any issues...

How can I fix it ?

**Comment by davidsblom** [comment]
Thanks for mentioning this problem. You should be able to fix this by removing the fourth line of `Allwmake.firstInstall` script: `set -euox pipefail`
This setting checks whether a environment variable is set, but that's what being checked anyway, so a bug.

**Comment by davidsblom** [comment]
Fixed with commit 73e514cebc1d5739fc32717ccefa91198baacb31
