### ISSUE TITLE
Use relative paths to `src/include` for the consistent solvers

### ISSUE THREAD

**Issue by davidsblom** [davidsblom/FOAM-FSI#41]
@thijsgillebaart The solvers cannot find the include files right now in case the repository is checked out in a random directory.

**Comment by thijsgillebaart** [comment]
@davidsblom I know the problem. However, I'm not in favor of the relative path solution.... I see two other options: 
1. put the src folder (as link) in $WM_PROJECT_USER_DIR
2. define a variable $FOAM_USER_SRC, which points to the correct location. This can be done in the Allwmake script maybe? Or some other script which can be coupled to the bashrc script of foam-extend-3.1

With the relative paths it's  a bit tricky especially if the directory tree gets bigger and people want to use parts of the code to make new code. Having a single variable pointing to the src tree (and application tree) or a top level one (i.e. $WM_PROJECT_USER_DIR) feels better. What do you think?

**Comment by davidsblom** [comment]
I'm in favour of a solution for which the user needs to do as little as possible. So the second option seems to be the best, I think. Then the `$FOAM_USER_SRC` variable should indeed be set by the `Allwmake` script.

**Comment by davidsblom** [comment]
Note that a simple `wmake` in the `applications/solvers/` probably does not work then. I'm not really convinced.

**Comment by thijsgillebaart** [comment]
I agree, relative path ensures the least trouble if you just "bluntly" compile it out of the box, which is good of course. But whenever you want to reorganize a couple of folder in your utitlities or application folder you would have to change the option files. So just copying a solver and compiling it somewhere else (with some minor changes) does not work.

Having an environment variable pointing to the src folder solves this. It indeed requires an extra step for the user to load this variable. We could add something to the prefs.sh in the foam-extend-3.1/etc/ folder by means of a (small) "install" script? 

I'm also not yet convinced of what would be the best way. It seems as if we would either favor users who never develop code themselves (even small changes in solvers) or favor developers by making cleaver use of environment variables.

**Comment by davidsblom** [comment]
Hmm. Most probably, our users are gonna be developers. In case we get questions about the environment variable, we could write a wiki page on it. Still seems a bit far fetched, since if you're gonna copy the solvers, you'll have some developer skills I presume. 

David

**Comment by davidsblom** [comment]
Use Allwmake_firstInstalll

**Comment by MakisH** [comment]
In case anyone receives errors during building, like

```
consistentIcoFoam.C:26:42: fatal error: readAutoPISOControls.H: No such file or directory
...
createFields.H:35:22: fatal error: createUf.H: No such file or directory
...
consistentPimpleFoam.C:24:44: fatal error: readAutoPIMPLEControls.H: No such file or directory
...
consistentSimpleSRFAbsFoam.C:5:25: fatal error: SRFModelAbs.H: No such file or directory
```

make sure that you have set the environment variable `FOAM_USER_SRC` to the `src/` directory of FOAM-FSI.

I had this problem since I ran the `Allwmake` script manually, in order to resume a failed build, which I had started with `Allwmake.firstInstall`. This variable is set in the beginning of the `Allwmake.firstInstall`.
