### ISSUE TITLE
Add CPU formulation for RBF interpolation.

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#66]
For comparison, implement a CPU formulation of the RBF interpolation. No Hhat will be constructed and the full set of equations is solved each time.

**Comment by thijsgillebaart** [comment]
Add two ways: 

1. calculate coefficients each time and recalculate Phi (or better: rows of Phi) each time
2. save inverse, but recalculate Phi (or better: rows of Phi).

**Comment by davidsblom** [comment]
punt 2 is implemented in the master branch.

**Comment by davidsblom** [comment]
example `dynamicMeshDict`:

```
dynamicFvMesh dynamicMotionSolverFvMesh;

solver RBFMeshMotionSolver;

movingPatches ( wall );

staticPatches ( );

fixedPatches ( outlet inlet );

coarsening
{
  enabled true;
  tol 1.0e-3;
  minPoints 10;
  maxPoints 2000;
  livePointSelection true;
  tolLivePointSelection 1.0e-2;
  exportSelectedPoints false;
}

interpolation
{
  function TPS;
  polynomial false;
  cpu true;
  fullCPU true;
}
```
