### ISSUE TITLE
Add possibility to use mesh points instead of face centres as boundary points for RBF mesh deformation

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#67]
For parallel processing this is difficult because of the shared points. However, globalMeshData should help with this.

**Comment by davidsblom** [comment]
which function are you actually thinking about? I found the file `pointProcAddressing ` which provides a global label per point. this file should then be read by every processor.
The most straightforward implementation is to use the points for the fixedPatches/staticPatches and keep the moving patches as defined in the face centers. Then all the fixedPatched/staticPatches can simply be gathered on every processor, and the `std::sort` can be applied right away since the displacement is alway zero.

**Comment by davidsblom** [comment]
I've started working on the cell vertices based implementation for the static and fixed patches with branch `rbfMeshMotion`. currently doesn't work at all :)

the method `sharedPointGlobalLabels ` could be useful.

**Comment by davidsblom** [comment]
closed by #72. The moving patches are still defined on the face centers. The fixed and static patches are now defined as the face vertices. The parallel implementation is also working fine.

@thijsgillebaart Can you check whether this works with your cases? In particular the airfoil with moving flap. Note that the moving patches are still defined on the face centers.

**Comment by thijsgillebaart** [comment]
Did you merge it into master branch?

**Comment by davidsblom** [comment]
yep

**Comment by thijsgillebaart** [comment]
Ik heb implementatie getest en werkt goed volgens mij. Heb even naar code zitten kijken en vrees misschien wel dat het erg duur wordt voor grotere meshes met alle “find” ’s in loops. Hoeft natuurlijk maar 1 keer, maar toch ;).

**Comment by thijsgillebaart** [comment]
Oh ja, en voor de surface correctie op de moving boundaries is het uiteindelijk beter om surface punten ipv faceCentres te verplaatsen in de hele RBF methode. Is dat voor jou een groot probleem? Kunnen misschien een switch maken in de code die alleen wij weten :D?

**Comment by davidsblom** [comment]
prima om ze dan gewoon allebei te implementeren. heb je ergens een testcase + solver staan die ik kan gebruiken om het te testen? 

klopt inderdaad dat het niet de meest snelle methode is op dit moment, weet alleen geen betere methode op dit moment. suggesties zijn uiteraard welkom.

**Comment by thijsgillebaart** [comment]
Ik heb goede testcase gemaakt met patches die doorsneden, patches die op einde doorsneden worden, etc. Heb op dit moment nog niet bedacht hoe ik het het beste kan doen. Heb elke keer dat ik 1 case niet kan uitsluiten. Grootste probleem voor bewegende boundaries is dat je moet bijhouden welke patch point van welke processor waar de beweging in de globale displacement vector moet plaatsen. Maar is wel te doen met de manier waarop het nu is geïmplementeerd. En opzicht hoeft het maar 1 keer natuurlijk per run, dus geen ramp. Morgen kunnen we even filosoferen over andere oplossing.

**Comment by davidsblom** [comment]
zou je die test case en solver kunnen doorsturen? heb nu een implementatie, maar kan em nog niet testen.
Thanks!

**Comment by davidsblom** [comment]
heb em werkend, parallel, volledig vertices based in the rbfFaceVertices branch. zou je em kunnen testen op je cases of tie werkt? Thanks!

**Comment by thijsgillebaart** [comment]
kan branch niet vinden….

**Comment by davidsblom** [comment]
heb em net in de master gezet. ben op dit moment bezig om de master te
mergen naar rbf-dev

**Comment by davidsblom** [comment]
heb net alles gemerged naar de rbf-dev branch

**Comment by thijsgillebaart** [comment]
Ok, top. Ik rbf-dev zitten wel nog paar test dingen die nog niet helemaal
werken, dat je het ff weet
