### ISSUE TITLE
mapMesh fails to compile. Something with yaml

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#76]

**Comment by thijsgillebaart** [comment]
Probably was something with not correctly compiled yaml. Let's close this one.

**Comment by davidsblom** [comment]
I've merged the master branch into the rbf-dev branch. Therefore, the `mapMesh/Make/options` file is updated. Does this solve your problems?

**Comment by thijsgillebaart** [comment]
yes, it works now
