### ISSUE TITLE
problem with WendlandC6. If all points are used, error is larger than machine precision

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#78]
Not fully tested yet, but not working properly.

**Comment by davidsblom** [comment]
hmm. how big is the error? I'll add some more unit tests for the Wendland-C6.

**Comment by davidsblom** [comment]
found a paper with large tables of probably all wendland's radial basis functions. their definition is a bit different than the implementation we currently use.

http://eprints.maths.ox.ac.uk/1561/1/finalOR57.pdf

**Comment by davidsblom** [comment]
I implemented the Wendland functions as written in this paper:

http://www.sciencedirect.com/science/article/pii/S0021999109002721#

**Comment by davidsblom** [comment]
what I noticed, is that the coefficients for the C0, C2, and C4 are the same in both papers except for some scaling factor. However, the C6 coefficients are different between the two papers.

**Comment by davidsblom** [comment]
I've created a python script to see what the difference is, and it appears that the functions are described by Rendall and Allen are the same functions, except for the scaling constant.
The C6 functions are up to an error 1.0e-16 exactly the same, so machine precision.

``` python
#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np

y1 = np.zeros( 101 )
y2 = np.zeros( 101 )
x = np.zeros( 101 )

for i in np.arange( 101 ):
    x[i] = i / 101.0
    r = x[i]
    y1[i] = np.power( 1.0 - r, 8.0 ) * ( 15.0 + 120.0*r + 375.0*r*r + 480.0*np.power(r,3) ) / 332640.0
    y2[i] = np.power( 1.0 - r, 8.0 ) * ( 1.0 + 8.0*r + 25.0*r*r + 32.0*np.power(r,3) )

y1 /= y1[0]

print np.linalg.norm(y1 - y2)

fig = plt.figure()
plt.plot( x, y1, '-' )
plt.plot( x, y2, '--' )
plt.show()

```
