### ISSUE TITLE
compilation of precise does not work on TU desktop

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#82]
I get the following error:

scons: Reading SConscript files ...

Build options ...
(default)  builddir                  = build      Directory holding build files. ( /path/to/builddir )
(modified) build                     = release    Build type, either release or debug (release|debug)
(modified) compiler                  = mpicxx     Compiler to use.
(default)  omp                       = False      Enables OpenMP-based parallelization. (yes|no)
(default)  mpi                       = True       Enables MPI-based communication and running coupling tests. (yes|no)
(default)  sockets                   = True       Enables Socket-based communication. (yes|no)
(default)  boost_inst                = False      Enable if Boost is available compiled and installed. (yes|no)
(default)  spirit2                   = True       Used for parsing VRML file geometries and checkpointing. (yes|no)
(modified) petsc                     = False      Enable use of the Petsc linear algebra library. (yes|no)
(modified) python                    = False      Used for Python scripted solver actions. (yes|no)
(default)  gprof                     = False      Used in detailed performance analysis. (yes|no)
... done

Environment variables used for this build ...
(have to be defined by the user to configure build)
(modified) PRECICE_BOOST_ROOT        = /home/thijsgillebaart/repositories/foam/src/thirdParty/boost_1_53_0
(modified) PRECICE_MPI_LIB_PATH      = /home/thijsgillebaart/foam/foam-extend-3.1/ThirdParty/packages/openmpi-1.6.5/platforms/linux64GccDPOpt/lib
(modified) PRECICE_MPI_LIB           = mpi     
(modified) PRECICE_MPI_INC_PATH      = /home/thijsgillebaart/foam/foam-extend-3.1/ThirdParty/packages/openmpi-1.6.5/platforms/linux64GccDPOpt/include
(default)  PRECICE_PTHREAD_LIB_PATH  = /usr/lib
(default)  PRECICE_PTHREAD_LIB       = pthread 
(default)  PRECICE_PTHREAD_INC_PATH  = /usr/include
... done

Configuring build variables ...
Checking whether the C++ compiler works... no

**Comment by davidsblom** [comment]
Best idea would be to use the system installed MPI installation.

**Comment by davidsblom** [comment]
Werkte dit al, of niet?
